baseURL = 'https://til.softinio.com/'
languageCode = 'en'
title = 'Salar Rahmanian: Today I Learned | TIL'

enableRobotsTXT = true
enableEmoji = true
paginate = 10

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[module]
[[module.imports]]
  path = 'github.com/softinio/hugo-flex'

