color =  "orange"           # Any color in CSS syntax
width =  "52rem"          # Any length in CSS syntax
rss =  """To subscribe to this RSS feed, copy its address and paste it into your
  favorite feed reader."""
summaries =  false      # Set to true to show summaries of posts on homepage
divider =  false          # Set to false to remove divider below posts on homepage
schema =  true         # Set to true to add Schema.org metadata
opengraph =  true      # Set to true to add Open Graph metadata
twittercards =  true   # Set to true to add Twitter Cards metadata
substackurl = "https://notes.softinio.com"

[giscus]
	repo = "softinio/til"
	repoid = "R_kgDOIxwp4w"
	category = "Comments"
	categoryid = "DIC_kwDOIxwp484CTmOz"

[matomo_analytics]
	enable = true # To enable matomo analytics change to `true`.
	websiteDomain = "til.softinio.com" # Set the domain name of your website, in most cases same as your base URL this is required.
	matomoDomain = "softinio.dev/matomo/" # Set to Matomo domain

	matomoSiteID = "4" # Default is set to 1, change this to the siteid being tracked

